### ISSUE TITLE
Allow "XSpec Run" from the view

### ISSUE THREAD

**Issue by raducoravu** [xspec/oXygen-XML-editor-xspec-support#15]
Feedback from @jelovirt on Slack:

> Can’t make those plugins work. I installed both, they report as “installed” in the add-on admin and what I get is just this. I do see the new "XSpec Report" transtype, but when I run it, it completes successfully and nothing is shown in the new XSpec window.

So the view should be able to run the first xspec all by itself.

**Comment by AlexJitianu** [comment]
You can run the XSpec directly from the view. The XSpec is chosen as such:
1. The current selected editor, if it's an XSpec file
2. The previously run XSpec file
3. It will present a file chooser and execute what the user selects in it
