### ISSUE TITLE
Error XTSE0660: Duplicate named template

### ISSUE THREAD

**Issue by nkutsche** [xspec/oXygen-XML-editor-xspec-support#20]
This error occurs any time, if there are two scenarios with the same label in one XSpec file.

Well, for example:

```
<x:scenario label="test 1">
    
</x:scenario>
<x:scenario label="test 1">
    
</x:scenario>
```

The error occurs independently of the position or level of the scenarios. For instance they can also be nested into other scenarios.

This happens with the plugin only. The XSpec standard transformation scenario works fine with this.

Tested in oXygen versions 19.0 and 18.1 (both full & developer)

**Comment by AlexJitianu** [comment]
It is something that I've introduced in: [Issue 17](https://github.com/xspec/oXygen-XML-editor-xspec-support/issues/17). I've overridden the template name generation so I can control which templates are invoked through a driver XSLT that imports the compiled XSLT. When I closed the issue I said "the chances for two scenarios to have the same name are pretty slim so I've decided to leave it like this for now". Boy, was I wrong!!!

**Comment by nkutsche** [comment]
Ok, I understand. :-)

Well, I think it is not a bad requirement to have unique labels, but: 

1. I took a while, until I found the reason for the duplicated templates. So at least a (Schematron) validtion would help. I think it can happen very easy, during dirty work on your XSpec script (just copy a scenario, make some changes, try it out - and fail, because you didn't change the label...)

2. In my case I have two scenarios as Test groups and inside I test similar stuff with different sub scenarios. So the sub scenarios have unique labels inside of the group, but not in the whole sheet:

```
<x:scenario label="group 1">
	<x:scenario label="test 1">...</x:scenario>
	<x:scenario label="test 2">...</x:scenario>
</x:scenario>
<x:scenario label="group 2">
	<x:scenario label="test 1">...</x:scenario>
	<x:scenario label="test 2">...</x:scenario>
</x:scenario>
```
So one (simple i hope) enhancement would be, to take the nested scenario labels into account for the template names.

**Comment by AlexJitianu** [comment]
Both of these points are valid. 
1. I'm sorry for the wasted time... I supposed I could also analyze the exceptions and if the "XTSE0660" code is present I could give a hint about the possible cause.
2. Yes, I can definitely take the labels of the ancestors into account when generating the ID.
I'll do these as soon as I have some spare time.

**Comment by nkutsche** [comment]
Thanks Alex! Don't worry about my time. It is normal for me to I try to understand an error, before I post it somewhere. I just wanted to point out, how helpful a validation or a concrete error message would be for this issue.

**Comment by nkutsche** [comment]
Hi Alex,

just an annotation to this. I run in the same problem, if I use x:like for one scenario, which contains other scenarios.

Example:

```
<x:scenario label="Shared" shared="yes">
	<x:scenario label="Sub scenario">
		<x:expect label="copy">
			<table/>
		</x:expect>
	</x:scenario>
</x:scenario>
<x:scenario label="Scenario 1">
	<x:context>
		<table class="xyz"/>
	</x:context>
	<x:like label="Shared"/>
</x:scenario>
<x:scenario label="Scenario 2">
	<x:context>
		<table class="abc"/>
	</x:context>
	<x:like label="Shared"/>
</x:scenario>
```

Scenario 1 and 2 are using the scenario "Shared", "Shared" contains other scenarios.

With the Ant XSpec framework it works, with the plugin I get the Duplicate named template error. 

Maybe, this should be respected during the fix. I think this is a real case, though it is special. My use case: I have a complex test scenario tree and want to test two different context variants. The differences shouldn't have an influence of the tests.

Best Regards,
Nico

**Comment by AlexJitianu** [comment]
It took a lot longer than anticipated but I finally managed to fix (hopefully) the template ID generation. 
@nkutsche if you feel lucky, you can update to the new version :) . If you go to *Help->Check for addons updates...* you should be able to install the new version. The new version is available at the same update site:
https://raw.githubusercontent.com/xspec/oXygen-XML-editor-xspec-support/master/build/update_site.xml

**Comment by nkutsche** [comment]
Hi Alex, 

thanks for the fix! I definitly will update it after my vacation.

Best Regards, 
Nico
