### ISSUE TITLE
XML Diff Viewer with capitals in element names

### ISSUE THREAD

**Issue by nkutsche** [xspec/oXygen-XML-editor-xspec-support#21]
Issue taken over from [another GitHub project](https://github.com/AlexJitianu/oXygen-XML-editor-xspec-support/issues/1), but still present:

When I use the Diff function to compare the expected with the current result in the Oxygen XML Diff Viewer, all element names was converted into lower case.

This is my scenario:
```
<x:scenario label="test">
	<x:context>
		<CAPS>CAPS</CAPS>
	</x:context>
	<x:expect label="identity result">
		<Caps>CAPS</Caps>
	</x:expect>
</x:scenario>
```
I get in the Oxygen XML Diff:

As result:
```
<caps>CAPS</caps>
```

As expected:
```
<caps>CAPS</caps>
```

**Comment by AlexJitianu** [comment]
I had to escape the expected/actual XML fragments in the generated HTML in order to keep the upper cases. I'll do another release so if this issue still bothers you, you can update the plugin.
