### ISSUE TITLE
XSLT error results in empty pane

### ISSUE THREAD

**Issue by tofi86** [xspec/oXygen-XML-editor-xspec-support#24]
If the tested XSLT produces an error (e.g. because of a `document($uri)` function where the `$uri` can't be accessed) the result pane is empty, no error is thrown and you have no chance to debug but install xspec as standalone application.

This happens with latest release, tested yesterday.

**Comment by AlexJitianu** [comment]
It would definitely be good to get feedback. I'll look into it and see how I can intercept the failure. Meanwhile, what you can do in this situation, to present the console, is to click on the following icon that can be found on Oxygen's status bar (bottom-right).
[
![output](https://user-images.githubusercontent.com/7802649/36037437-734ca1dc-0dc5-11e8-8c8b-3d0226992db5.png)
](url)

**Comment by AirQuick** [comment]
If you add `@failonerror="true"` to [`<java>`](https://github.com/xspec/oXygen-XML-editor-xspec-support/blob/15a2475d042a9c7be50bff112f0d1cbc0fed6971/frameworks/xspec/oxygen-results-view/build_report.xml#L356), the error is caught.
(The attribute is going to be added by xspec/xspec#266.)

**Comment by AirQuick** [comment]
Looks like this is no longer reproduced on 1.2.1. (The `ANT [XSpec for XSLT]` pane opens automatically on failure. There you can see what the actual error is.)

**Comment by AlexJitianu** [comment]
Version 1.21. of the plugin bundles version 1.2.0 of XSpec. I probably ported the `@failonerror` fix as well (I see it it in the `build_report.xml`).
