### ISSUE TITLE
Diff action shows a "/" in first line

### ISSUE THREAD

**Issue by tofi86** [xspec/oXygen-XML-editor-xspec-support#29]
Testcase: https://github.com/xspec/xspec/issues/227

The test fails for whatever reasons will come up in the named issue.

However, when clicking the "Diff" button, the oXygen Diff shows a `/` character in the first line of "expected", which isn't contained in the expected file:

![bildschirmfoto 2018-07-24 um 12 54 01](https://user-images.githubusercontent.com/365118/43133960-aab85be6-8f40-11e8-8024-ccdaddb9f649.png)

**Comment by tofi86** [comment]
Also, the `<test:ws>` elements shouldn't be visible, right?

**Comment by AlexJitianu** [comment]
> Also, the <test:ws> elements shouldn't be visible, right?

I'm not sure what to do with them... They look like they contain the original spacing/indent but if that's the case I would have expected them to appear for each indent. If I look inside the intermediate ***-result.xml** file I see one such **test:ws** element between each two tags from the **x:expect** element, but in the **x:result** one there are **text:ws** elements missing (for example between the <html> and <head> element).

do you have any suggestions? Should I remove, unwrap or keep them as the only indent (and discard the other indent nodes).

**Comment by tofi86** [comment]
> I'm not sure what to do with them... They look like they contain the original spacing/indent

That's what it is indeed: https://github.com/xspec/xspec/issues/227#issuecomment-407469485
But I also had to learn it in first place...

So what to do? I'm undecided... From a technical point I understand why it's important to have this information around, but from a UX perspective I was (and still am) a bit confused to see it...

Removing all other textnodes and unwrapping the original whitespace nodes seems like a nice idea...

@cirulls @AirQuick do you have an idea? Or should @AlexJitianu just leave the diff as is? I would be fine with it now that I know what the `test:ws` elements are for... but I could also image the solution mentioned above...

**Comment by AirQuick** [comment]
The whitespace-only text node in **test:ws** is significant. So it shouldn't be removed.

We could just unwrap it. But the screenshot suggests that the problem happens on oXygen Diff, right? Then I recall that oXygen Diff has **Format and Indent Both Files** button (which itself is quite useful). If the user hits the button, I'm afraid the unwrapped whitespace-only text node is lost.

Another option might be unwrapping **test:ws** and replacing its whitespace-only text node with a string just like [the HTML report does](https://github.com/xspec/xspec/blob/b28c01e4854ccab364b9b2cd6c87d72ace7a1040/src/reporter/format-utils.xsl#L156-L172). In this case, the user may still wonder what this `\n\r\t.` string is... But I guess at least it isn't too ugly nor lost by **Format and Indent**.

**Comment by AlexJitianu** [comment]
I've followed @AirQuick's suggestions and I've replaced test:ws with a string just like the HTML report does. The next plugin build will contain the fix.
