### ISSUE TITLE
x:expect in xspec 

### ISSUE THREAD

**Issue by neeraj0015** [xspec/oXygen-XML-editor-xspec-support#32]
How can we Handle multiple xpath relate to one node contain many child in one scenario and how to execute them.

<test>
<url>
  <remotelink href="www.uspto.gov/trademarks/teas/index.jsp" hrefclass="http"
   newwindow="YES">http://www.uspto.gov/trademarks/teas/index.jsp</remotelink>
 </url>
 <url>
  <remotelink href="www.lawandarts.co.uk/" hrefclass="http">
   <emph typestyle="it">
    <emph typestyle="un">www.lawandarts.co.uk</emph>
   </emph>
  </remotelink>
 </url>
</test>

xpath:
1: test/url[1]/remotelink[1] 
2: test/url[2]/remotelink[1][child::emph]

Xspec scenario:

<x:scenario label="testing of url/remotelink to url (id-CCCC-10464)">
        <x:context select="/CASEDOC/docinfo[1]/url[1]/remotelink[1] or /CASEDOC/docinfo[1]/url[2]/remotelink[1][child::emph]" href="test.xml">
        </x:context>
        <x:expect label="testing of url/remotelink to url (id-CCCC-10464)">
            <url normval="http://www.uspto.gov/trademarks/teas/index.jsp">http://www.uspto.gov/trademarks/teas/index.jsp</url>
        </x:expect>
        <x:expect label="testing of url/remotelink/emph to url (id-CCCC-10464)">
            <url normval="http://www.lawandarts.co.uk">www.lawandarts.co.uk</url>
        </x:expect>
        
    </x:scenario>

**Comment by AirQuick** [comment]
Are you looking for something like this?

**test.xsl**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet exclude-result-prefixes="#all" version="2.0"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:template as="text()" match="remotelink">
		<xsl:value-of select="(child::emph, .)[1]" />
	</xsl:template>
</xsl:stylesheet>
```

**test.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CASEDOC>
	<docinfo>
		<url>
			<remotelink>http://www.uspto.gov/trademarks/teas/index.jsp</remotelink>
		</url>
		<url>
			<remotelink>http://<emph>www.lawandarts.co.uk</emph>/</remotelink>
		</url>
	</docinfo>
</CASEDOC>
```

**test.xspec**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<x:description stylesheet="test.xsl" xmlns:x="http://www.jenitennison.com/xslt/xspec">
	<x:scenario label="testing">
		<x:context href="test.xml" />

		<x:scenario label="remotlink w/o child::emph">
			<x:context select="/CASEDOC/docinfo[1]/url[1]/remotelink[1]" />
			<x:expect label="transformed to url"
				>http://www.uspto.gov/trademarks/teas/index.jsp</x:expect>
		</x:scenario>

		<x:scenario label="remotelnk w/ child::emph">
			<x:context select="/CASEDOC/docinfo[1]/url[2]/remotelink[1][child::emph]" />
			<x:expect label="extracts emph">www.lawandarts.co.uk</x:expect>
		</x:scenario>
	</x:scenario>
</x:description>
```


**Result**
```console
C:\test>bin\xspec.bat test.xspec
...
passed: 2 / pending: 0 / failed: 0 / total: 2
```

**Comment by neeraj0015** [comment]
Hi,

Thanks for this.

**Comment by AlexJitianu** [comment]
It don't think there is anything to be done here anymore.
