### ISSUE TITLE
Version 1.6.0?

### ISSUE THREAD

**Issue by AirQuick** [xspec/oXygen-XML-editor-xspec-support#40]
https://www.oxygenxml.com/xml_editor/whatisnew22.1.html#22.1Add-ons
> XSpec Add-on Updated to Support XSpec Version 1.6.0

But when I open **Install new add-ons**, only `1.5.0` is listed.

**Comment by AlexJitianu** [comment]
Thank you for reporting this slip up! The 1.6.0 release should now be offered on the update site.
