### ISSUE TITLE
processing terminated by xsl:message while atomizing the value of variable $successful

### ISSUE THREAD

**Issue by thendarion** [xspec/oXygen-XML-editor-xspec-support#45]
`Processing terminated by xsl:message at line XX in xsl-compiled.xsl. Found while atomizing the value of variable $successful`

what does that even mean? :D

my tests run fine in oXygen without this plugin

**Comment by AirQuick** [comment]
I guess the actual error message here is being swallowed by a Saxon [bug](https://saxonica.plan.io/issues/4621).
I'd suggest running the command line version of XSpec with Saxon 9.9.1.8 or 10.5 and inspecting the actual error message.

**Comment by thendarion** [comment]
thanks. I'll do that :)

I'm closing this ticket then. I'll reopen it if it turns out to be anything but a Saxon bug

**Comment by AirQuick** [comment]
Or the actual error message may be emitted prior to your cited message.

In the following example, `ERROR in x:expect ('my scenario my expectation'): Boolean @test must not be accompanied by @as, @href, @select, or child node.` is the actual error message:

```console
     [echo] Running XSLT Tests...

     [java] Testing with SAXON EE 9.9.1.7
     [java] my scenario
     [java] my expectation
     [java] ERROR in x:expect ('my scenario my expectation'): Boolean @test must not be accompanied by @as, @href, @select, or child node.
     [java] Error evaluating (($result, ...)) on line 134 column 45 of select-compiled.xsl:
     [java]   XTMM9000: Processing terminated by xsl:message at line 134 in select-compiled.xsl. Found
     [java]   while atomizing the value of variable $successful
```

In another example, `ERROR in x:expect ('my scenario my expectation'): Non-boolean @test must be accompanied by @as, @href, @select, or child node.` is the actual error message:

```console
     [echo] Running XSLT Tests...
     [java] Testing with SAXON EE 9.9.1.7
     [java] my scenario
     [java] my expectation
     [java] ERROR in x:expect ('my scenario my expectation'): Non-boolean @test must be accompanied by @as, @href, @select, or child node.
     [java] Error evaluating (($result, ...)) on line 157 column 45 of node-compiled.xsl:
     [java]   XTMM9000: Processing terminated by xsl:message at line 157 in node-compiled.xsl. Found
     [java]   while atomizing the value of variable $successful
```

Those error messages mean that your `x:expect/@test` is not consistent. Such inconsistent `@test` was allowed in older versions of Xspec, but is no longer allowed in the recent versions of XSpec. See https://github.com/xspec/xspec/pull/1245#issue-493736793 for details. Particularly its **Example** section.
