### ISSUE TITLE
Not compatible with oXygen 26

### ISSUE THREAD

**Issue by AirQuick** [xspec/oXygen-XML-editor-xspec-support#52]
Need to add Saxon 12 to the classpath.
See xspec/xspec#1810.

**Comment by AlexJitianu** [comment]
I already relaxed the Saxon classpath entry to work with Oxygen future versions:
https://github.com/xspec/oXygen-XML-editor-xspec-support/commit/27f782caa1716caf9c8b6b993cd387c0240e1231
