### ISSUE TITLE
Helper view reports "Running..." although transformation has already failed

### ISSUE THREAD

**Issue by raducoravu** [xspec/oXygen-XML-editor-xspec-support#6]
If I click for example the "XSpec Run" toolbar button when having an XML document opened, transformation fails but view seems to indicate "Running..."

**Comment by raducoravu** [comment]
I also get this warning in the console:

      logger.warn("Transformation ended with error");

**Comment by AlexJitianu** [comment]
I think I've fixed it. In this particular situation a choose will appear to select the XSpec file. I also took care to reset the "Running" label in the different result situations.
